### ISSUE TITLE
com.opennaru.khan.khan-counter is missing!! Compile is not possible.

### ISSUE THREAD

**Issue by Jooho** [opennaru-dev/khan-session#16]
From pom.xml in khan-session-core module, it needs khan-counter module but it is missing. Hence, whole project is not possible to compile.
~~~
<dependency>
            <groupId>com.opennaru.khan</groupId>
            <artifactId>khan-counter</artifactId>
            <version>1.0.0</version>
        </dependency>
~~~

**Comment by nameislocus** [comment]
KHAN counter is in here https://github.com/nameislocus/khan-counter
You must run 'mvn install' with khan-counter, before  compile khan-session project.
